mysite/blog/urls.py
from django.urls import path

from .import views

app_name = 'blog'

urlpatterns = [
    
    path('',views.post_list,name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('search/',views.search,name='search'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class PublishedManager(models.Manager):

    def get_queryset(self):

        return super(PublishedManager,self).get_queryset().filter(status='published')


class Post(models.Model):

    STATUS_CHOICES = (('draft','Draft'),('published','Published'))

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name='blog_posts')
    image = models.ImageField(upload_to='images/%y/%m/%d/',default=False)
    secondary_image= models.ImageField(upload_to='secondary/images/%y/%m/%d/',default=False)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')



    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title


    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[self.publish.year,self.publish.month,self.publish.day,self.slug])
    


class Comment(models.Model):

    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms
from django.forms import fields

from .models import Comment,Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','body')


class PostForm(forms.ModelForm):
    class Meta:

        model = Post
        fields = ('title','author','body')

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.postgres.search import SearchVector
# Create your views here.
from .models import Post,Comment
from .forms import CommentForm,PostForm


def search(request):

    if request.method=="POST":

        searched = request.POST['searched']

        results = Post.objects.filter(title__icontains = searched)
        
        return render (request,'blog/post/search.html',{'searched':searched,'results':results})

def post_list(request):

    posts = Post.published.all()


    

    return render (request,'blog/post/list.html',{'posts':posts})


    

def post_detail(request,year, month , day , post):

    post = get_object_or_404(Post,slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)

    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():

            new_comment = comment_form.save(commit=False)

            new_comment.post = post

            new_comment.save()

    else:
        comment_form = CommentForm()

    return render (request,'blog/post/detail.html',{'post':post,'comments':comments,'new_comment':new_comment,'comment_form':comment_form})

mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}
              
            {% endblock title %}
        </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>

    <body>

        <div class="navbar">
            <a class="nav" href="{% url 'blog:post_list' %}" >Home</a>
            <form action="{% url 'blog:search' %}" method="POST">
                {% csrf_token %}
                <div class="input-group rounded">
                <input name='searched' class="form-control rounded" type="search" placeholder="Search" aria-label="Search" name="" id="ss"> 
                <input class="btn btn-secondary" type="submit" value="Search" name="" id="">
                </div>
            </form>
        </div>
        <div class="container">
            {% block content %}
              
            {% endblock content %}
        </div>
        <div class="sidebar">

        </div>
    </body>

    <style>

        .navbar{

            padding: 10px;
            background-color: rgb(33, 110, 197);
            text-decoration: none;
            float:inherit;
            
        }
       
        
        a.nav{
            text-decoration: none;
            font-size: 30px;
            
            font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
            color: rgb(255, 255, 255);

            
        }
        a.nav:hover{
            color: rgb(214, 214, 214);
        }
        .container{

            margin-top: 30px;
        }
    </style>
</html>

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}


{% block title %}
  {{ post.title }}
{% endblock title %}



{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
  {{ post.body|linebreaks }}

  {% with comments.count as total_comments %}
    <h2>{{ total_comments }} comment{{ total_comments|pluralize }} </h2>
  {% endwith %}

  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>There are no comments yet.</p>
  {% endfor %}

  {% if new_comment %}
    <h2>Your comment has been added. </h2>
    
    {% else %}
    <h2>Add a new comment</h2>
    <form method="POST">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input class="btn btn-primary" type="submit" value="Add comment" name="" id=""></p>
    </form>
  {% endif %}
{% endblock content %}

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}
  My blog 
{% endblock title %}
{% block content %}
  <h1>My Blog</h1>

  

  {% for post in posts %}
    <h2>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </h2>

    <div class="image">

      <a href="{{ post.get_absolute_url }}">
        {% if post.image %}
          <img src="{{ post.image.url }}" width="100%" alt="">
          {% else %} 
          <img src="" alt="no image ">
        {% endif %}
      </a>
    </div>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
{% endblock content %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block content %}

    {% if searched %}
      <h1>You searched for "{{ searched }}"</h1>
      <h3>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
        </h3>

      {% for result in results  %}

      <h2><a href="{{ result.get_absolute_url }}">{{ result }}</a></h2><br>
        
      {% endfor %}

    {% else %}

        <h1>You didn't search anything.</h1>
    {% endif %}
{% endblock content %}